env:
  node: true
root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: 'module'
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - ".eslintrc.yml"
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - never
